import "../app/styles/globals.css";
import "../app/styles/desktop.css";
import "../app/styles/tablet_large.css";
import "../app/styles/tablet_small.css";
import "../app/styles/mobile.css";

export const metadata = {
  title: "Tutor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
